package hibernatePackage;

import javax.persistence.*;

/*This Class is our family class. It is going to get
* and set the id, name, and date of birth
*  from out family table and hen display it to the user.*/

/*The block of code tell hibernate that this
* relates to a table by the name of family*/
@Entity
@Table(name="family")
public class Family {
    /*This is telling hibernate that this field
     * relates to the column "id" in our family
     * table. The Id and GenerateValue is very
     * important. It is telling hibernate that
     * the identity is being generated by the
     * database and without this, the program
     * will not work... yes, I am speaking
     * from experience... */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    /*This is telling hibernate that this field
    * relates to the column "name" in our family
    * table.*/
    @Column(name = "name")
    private String name;

    /*This is telling hibernate that this field
     * relates to the column "dob" in our family
     * table.*/
    @Column(name="dob")
    private String dob;

    /*This block of code represents the getters and
    * setters for the fields we are referencing
    * in the family table.*/
    public int getId() {
        return id;
    }
    public void setId(int id){
        this.id=id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name){
        this.name=name;
    }
    public String getDob() {
        return dob;
    }
    public void setDob(String dob){
        this.dob=dob;
    }

    /*This is our to string that is going to
    * print to the console to results of our
    * family table. It is going to display
    * the id number and the name.*/
    public String toString(){
        return Integer.toString(id) + " " + name + " " + dob;
    }

}